apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditservice-deployment
  labels:
    app: creditservice-deployment
spec:
  selector:
    matchLabels:
      app: creditservice-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: creditservice-deployment
    spec:
      containers:
        - name: creditservice-service
          image: chimary/creditservice:latest
          ports:
            - containerPort: 8094
          env:
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_CREDIT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_CREDIT