apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditmonitoringservice-deployment
  labels:
    app: creditmonitoringservice-deployment
spec:
  selector:
    matchLabels:
      app: creditmonitoringservice-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: creditmonitoringservice-deployment
    spec:
      containers:
        - name: creditmonitoringservice-service
          image: chimary/creditmonitoringservice:latest
          ports:
            - containerPort: 8095
          env:
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_MONITORING
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_MONITORING