apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditmonitoringservice-deployment
  labels:
    app: creditmonitoringservice-deployment
spec:
  selector:
    matchLabels:
      app: creditmonitoringservice-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: creditmonitoringservice-deployment
    spec:
      containers:
        - name: creditmonitoringservice-service
          image: chimary/creditmonitoringservice
          ports:
            - containerPort: 8095