apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditservice-deployment
  labels:
    app: creditservice-deployment
spec:
  selector:
    matchLabels:
      app: creditservice-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: creditservice-deployment
    spec:
      containers:
        - name: creditservice-service
          image: chimary/creditservice
          ports:
            - containerPort: 8094