apiVersion: apps/v1
kind: Deployment
metadata:
  name: loantypeservice-deployment
  labels:
    app: loantypeservice-deployment
spec:
  selector:
    matchLabels:
      app: loantypeservice-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: loantypeservice-deployment
    spec:
      containers:
        - name: loantypeservice-service
          image: chimary/loantypeservice
          ports:
            - containerPort: 8093
          env:
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_LOAN
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_LOAN