apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdffileservice-deployment
  labels:
    app: pdffileservice-deployment
spec:
  selector:
    matchLabels:
      app: pdffileservice-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: pdffileservice-deployment
    spec:
      containers:
        - name: pdffileservice-service
          image: chimary/pdffileservice:latest
          ports:
            - containerPort: 8092
          env:
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_DOCUMENT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_DOCUMENT