server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: CalculateService
          uri: lb://CalculateService
          predicates:
            - Path=/api/calculate/**
        - id: creditService
          uri: lb://creditService
          predicates:
            - Path=/api/credit/**
        - id: EvaluationService
          uri: lb://evaluationService
          predicates:
            - Path=/api/evaluation/**
        - id: LoanTypeService
          uri: lb://LoanTypeService
          predicates:
            - Path=/loantype/**
        - id: pdfFileService
          uri: lb://pdfFileService
          predicates:
            - Path=/files/**
        - id: SimulatorService
          uri: lb://SimulatorService
          predicates:
            - Path=/api/simulator/**
        - id: userService
          uri: lb://userService
          predicates:
            - Path=/user/**